### ISSUE TITLE
Platform error light.beewi_light - Requirements for beewi_light not found: ['bluepy>=1.3.0'].

### ISSUE THREAD

**Issue by gchrisak** [bbo76/light.beewi#2]
Hello,

Im getting the bellow error when checking my configuration file:
Platform error light.beewi_light - Requirements for beewi_light not found: ['bluepy>=1.3.0']

  - platform: beewi_light
    name: my_light
    address: "98:5D:AD:##:##:##"

**Comment by gchrisak** [comment]
Hello again,

Seems to be related to the bellow breaking change:
https://www.home-assistant.io/blog/2022/07/06/release-20227/#breaking-changes

**Comment by bbo76** [comment]
Hello, yes you are true, the new system to manage bluetooth is a problem for this project. I have not the time to maintain more this project, but you are free to fork it and do the job. Sorry about this.
